version: "3.8"

services:
  core:
    build:
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    user: 1000:1000
    volumes:
      - ../../:/home/pn/AwsCdkTemplate
    command: poetry run python3 -m http.server 6543
